import { useState } from 'react'
import { Bot, ChevronDown, Code2, Crop, Eye, FileCode2, Image, LayoutTemplate, Monitor, Play, Redo2, RotateCw, Save, SlidersHorizontal, Smartphone, Sparkles, Tablet, TerminalSquare, Type, Undo2 } from 'lucide-react'
import { Badge, Button, Card, PageHeader } from '../components/ui'
import { useApp } from '../context/AppContext'

export function SiteEditorPage() {
  const { notify } = useApp()
  const [device, setDevice] = useState('desktop')
  const [headline, setHeadline] = useState('Transforme projetos complexos em progresso claro.')
  return <div className="page page--wide"><PageHeader title="Editor de sites" description="Canvas visual para criar portais e páginas de clientes." actions={<><Button><Eye size={15} /> Pré-visualizar</Button><Button variant="primary" onClick={() => notify('Página salva localmente.', 'success')}><Save size={15} /> Salvar</Button></>} /><div className="editor-toolbar"><div><Button><Undo2 size={15} /></Button><Button><Redo2 size={15} /></Button></div><div className="segmented-control"><button className={device === 'desktop' ? 'active' : ''} onClick={() => setDevice('desktop')}><Monitor size={15} /></button><button className={device === 'tablet' ? 'active' : ''} onClick={() => setDevice('tablet')}><Tablet size={15} /></button><button className={device === 'mobile' ? 'active' : ''} onClick={() => setDevice('mobile')}><Smartphone size={15} /></button></div><Badge tone="green">Rascunho salvo</Badge></div><div className="visual-editor"><Card className="editor-panel"><h3>Blocos</h3>{[['Texto', Type], ['Imagem', Image], ['Botão', Play], ['Seção', LayoutTemplate]].map(([label, Icon]) => <button key={label as string}><Icon size={16} />{label as string}</button>)}<div className="editor-panel__divider" /><h3>Páginas</h3><button className="active"><span>Home</span><ChevronDown size={14} /></button><button>Serviços</button><button>Contato</button></Card><div className={`site-canvas site-canvas--${device}`}><div className="site-preview"><nav><strong>Northstar</strong><span>Serviços&nbsp;&nbsp; Projetos&nbsp;&nbsp; Contato</span><Button>Solicitar orçamento</Button></nav><section><Badge tone="purple">Especialistas em pisos</Badge><h1>{headline}</h1><p>Planejamento, execução e acompanhamento em uma experiência simples para sua equipe e seus clientes.</p><div><Button variant="primary">Começar projeto</Button><Button>Ver trabalhos</Button></div></section><div className="site-preview__stats"><span><strong>240+</strong><small>projetos entregues</small></span><span><strong>4.9/5</strong><small>avaliação média</small></span><span><strong>12 anos</strong><small>de experiência</small></span></div></div></div><Card className="editor-panel editor-panel--right"><h3>Propriedades</h3><label>Texto<textarea rows={5} value={headline} onChange={(event) => setHeadline(event.target.value)} /></label><label>Alinhamento<select><option>Esquerda</option><option>Centralizado</option></select></label><label>Espaçamento<input type="range" min="16" max="96" defaultValue="48" /></label><div className="editor-panel__divider" /><h3><Sparkles size={16} /> Alterar com IA</h3><textarea rows={4} placeholder="Deixe o título mais premium e direto..." /><Button variant="primary" onClick={() => setHeadline('Seu projeto, conduzido com clareza do início ao fim.')}>Aplicar sugestão</Button></Card></div></div>
}

export function ImageEditorPage() {
  const { notify } = useApp()
  const [brightness, setBrightness] = useState(100)
  const [contrast, setContrast] = useState(100)
  const [rotate, setRotate] = useState(0)
  return <div className="page page--wide"><PageHeader title="Editor de imagens" description="Ajustes visuais responsivos para materiais de projetos e clientes." actions={<><Button><Undo2 size={15} /> Desfazer</Button><Button variant="primary" onClick={() => notify('Imagem exportada em PNG.', 'success')}><Save size={15} /> Exportar</Button></>} /><div className="image-editor"><Card className="editor-panel"><h3>Ferramentas</h3>{[['Cortar', Crop], ['Girar', RotateCw], ['Texto', Type], ['Ajustes', SlidersHorizontal], ['Gerar com IA', Sparkles]].map(([label, Icon]) => <button key={label as string} onClick={() => label === 'Girar' && setRotate((value) => value + 90)}><Icon size={16} />{label as string}</button>)}</Card><div className="image-canvas"><div className="image-art" style={{ filter: `brightness(${brightness}%) contrast(${contrast}%)`, transform: `rotate(${rotate}deg)` }}><span>WORKFORGE</span><h2>Projetos com mais clareza.</h2><p>Menos ruído. Mais progresso.</p></div></div><Card className="editor-panel editor-panel--right"><h3>Ajustes</h3><label>Brilho <strong>{brightness}%</strong><input type="range" min="50" max="150" value={brightness} onChange={(event) => setBrightness(Number(event.target.value))} /></label><label>Contraste <strong>{contrast}%</strong><input type="range" min="50" max="150" value={contrast} onChange={(event) => setContrast(Number(event.target.value))} /></label><label>Saturação <strong>100%</strong><input type="range" min="0" max="200" defaultValue="100" /></label><div className="editor-panel__divider" /><Button onClick={() => { setBrightness(100); setContrast(100); setRotate(0) }}>Restaurar ajustes</Button></Card></div></div>
}

export function CodeStudioPage() {
  const { notify } = useApp()
  const [tab, setTab] = useState('Dashboard.tsx')
  const files = ['src', 'components', 'AppShell.tsx', 'Dashboard.tsx', 'Timeline.tsx', 'styles.css']
  return <div className="page page--wide"><PageHeader title="Code Studio" description="Ambiente visual preparado para uma futura integração com um agente de desenvolvimento." actions={<><Button><Save size={15} /> Salvar</Button><Button variant="primary" onClick={() => notify('Preview atualizado.', 'success')}><Play size={15} /> Executar</Button></>} /><div className="code-studio"><aside className="code-tree"><header><strong>EXPLORER</strong><button>•••</button></header>{files.map((file, index) => <button className={file === 'Dashboard.tsx' ? 'active' : ''} key={file} style={{ paddingLeft: `${12 + Math.min(index, 2) * 12}px` }}><FileCode2 size={14} />{file}</button>)}</aside><section className="code-editor"><div className="code-tabs">{['Dashboard.tsx', 'styles.css'].map((item) => <button className={tab === item ? 'active' : ''} onClick={() => setTab(item)} key={item}><Code2 size={13} />{item}</button>)}</div><pre><code>{tab === 'Dashboard.tsx' ? `export function Dashboard() {\n  const insights = useWorkspaceInsights()\n\n  return (\n    <Page title="Dashboard">\n      <MetricGrid data={insights.metrics} />\n      <ActivityFeed items={insights.activity} />\n      <AIInsights risks={insights.risks} />\n    </Page>\n  )\n}` : `.card {\n  border: 1px solid var(--border);\n  border-radius: 14px;\n  transition: border-color 160ms ease,\n              transform 160ms ease;\n}\n\n.card:hover {\n  border-color: var(--border-strong);\n  transform: translateY(-1px);\n}`}</code></pre><div className="terminal-panel"><header><span><TerminalSquare size={14} /> Terminal</span><Badge tone="green">Pronto</Badge></header><code>$ npm run dev<br />✓ VITE ready in 412 ms<br />➜ Local: http://localhost:4173/</code></div></section><aside className="code-chat"><header><Bot size={17} /><strong>AI Developer</strong></header><div className="code-chat__message"><p>Analisei o dashboard. Posso reduzir a densidade dos cards e melhorar a hierarquia sem alterar o conteúdo.</p><Button>Ver diff</Button></div><textarea rows={4} placeholder="Peça uma alteração..." /><Button variant="primary">Enviar</Button></aside></div></div>
}
